name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17", "1.16"]
    name: Go v${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: make test-ci

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: coverage.out
